### ISSUE TITLE
ImportError: cannot import name 'frdist'

### ISSUE THREAD

**Issue by nbro** [spiros/discrete_frechet#2]
If I execute the following script

```
import frechetdist

if __name__ == '__main__':
    P = [[1, 1], [2, 1], [2, 2]]
    Q = [[2, 2], [0, 1], [2, 4]]
    print(frechetdist.frdist(Q, P))
```

I get the following error

```
Traceback (most recent call last):
  File "C:/Users/User/Desktop/my_script.py", line 1, in <module>
    import frechetdist
  File "C:\Users\User\Desktop\venv\lib\site-packages\frechetdist\__init__.py", line 1, in <module>
    from . import frdist
ImportError: cannot import name 'frdist'
```

Even if I perform the import like `from frechetdist import frdist` I get the same error.

I am using Python 3.6.5. I installed your module using `pip install frechetdist` inside a virtual environment.

**Comment by spiros** [comment]
Thank you for spotting & reporting - clearly a bug. I've removed the package from PyPi until i can fix it - please use directly from the repository for now.

**Comment by spiros** [comment]
Hello - f92c4f0075ca0b81bf6470811be27820c1537b89 fixes this.

Thanks once again for spotting this. Please install latest version using pip.

Example:

```
spiros@tokidoki:~$python -m venv /tmp/avocado
spiros@tokidoki:~$source /tmp/avodaco/bin/activate
(avocado) spiros@tokidoki:~$pip install frechetdist
Successfully installed frechetdist-0.6
(avocado) spiros@tokidoki:~$python -c 'from frechetdist import frdist'
(avocado) spiros@tokidoki:~$python -c 'from frechetdist import frdist; print(frdist([[1,1], [2,1], [2,2]], [[2,2], [0,1], [2,4]]))'
2.0
```
