### ISSUE TITLE
Why doesn't this implementation support the comparison of two polylines of different sizes?

### ISSUE THREAD

**Issue by nbro** [spiros/discrete_frechet#3]
The implementation of the Frechet distance in [this other module](https://github.com/cjekel/similarity_measures/blob/master/similaritymeasures/similaritymeasures.py) apparently supports this.

**Comment by spiros** [comment]
Hm, let me check.

**Comment by williampiat3** [comment]
See #15 removing the same length constraint is straightforward and allows for a more general function

**Comment by spiros** [comment]
Have merged the PR, thank you @williampiat3
